//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodazba1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdazbaEntities1 : DbContext
    {
        public ProdazbaEntities1()
            : base("name=ProdazbaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<Prodazba> Prodazbas { get; set; }
        public virtual DbSet<Produkt> Produkts { get; set; }
    }
}
