//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodazba1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodazba
    {
        public int MarketId { get; set; }
        public int ProduktId { get; set; }
        public Nullable<int> Cena { get; set; }
    
        public virtual Market Market { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
